srCreation/Creation/Controllers/OfferController.cs
using srBiz;
using srEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Creation.Controllers
{
    public class OfferController : _Controller
    {

        public ActionResult Go(string Id)
        {
            OfferModel model = new OfferModel();
            model.AllOffers = BizOffer.GetOffers(Convert.ToInt64(Id));
            return View(model);
        }

        public ActionResult Create()
        {
            OfferModel model = new OfferModel();
            List<Offer> off = new List<Offer>();
            off.Add(new Offer());
            model.AllOffers = off;
            return View("CreateOffer", model);
        }
    }
}

srCreation/Creation/Views/Offer/CreateOffer.cshtml
@model srEntity.OfferModel

<h5>Create Offer</h5>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <table>
            <tr>
                <td>
                    Category
                </td>
                <td>
                    @Html.DropDownList("")
                </td>
            </tr>
        </table>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Go")
</div>

srCreation/Creation/Views/Offer/Go.cshtml
@using srEntity
@model OfferModel
@{
    Creation.Controllers._Controller cbase = ViewContext.Controller as Creation.Controllers._Controller;
}
<fieldset>
    @if (cbase.IsAdmin())
    {
        @Html.ActionLink("Create New Offer", "Create", "Offer", null, new { @class = "pull-right padding-right" })
        <div style="height:10px;clear:both;"></div>
    }
    <div id="dOfferListing">
        <ul>
            @if (Model.AllOffers != null && Model.AllOffers.Count() > 0)
            {
                foreach (Offer off in Model.AllOffers)
                {
                    <li>
                        <span class="pull-right SizeHalf">@off.CatName</span>
                        <div class="dOffEach">
                            @off.Title
                            <hr />
                            <p>
                                @if (off.Descn.Length > 100)
                                {
                                    @off.Descn.Substring(0, 100)
                                    <span>......</span>
                                }
                                else
                                {
                                    @off.Descn
                                }
                            </p>
                            <span id="sToggle" data-tog="0" data-show="Less" data-hide="More" class="pull-right SizeHalf btn">More</span>
                            <span>
                                Likes: @off.Likes <span class="padding-left" />
                                DisLikes: @off.DisLikes
                            </span>
                        </div>
                        <span class="pull-left SizeHalf">@off.ModOn</span>
                        <span class="pull-right SizeHalf">@off.ModBy</span>
                    </li>
                }
                if (Model.AllOffers.Count() == 1)
                {
                    @Html.Partial("_Cmnts", Model.AllOffers.First().Cmnts)
                }
            }
            else
            {
                <li>Sorry! No offer found!</li>
            }
        </ul>
    </div>
</fieldset>