srCreation/Creation/Controllers/NanoGenController.cs
using srEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Creation.Controllers
{
    public class NanoGenController : _Controller
    {
        public ActionResult Go()
        {
            NanoModel model = new NanoModel();
            model.NanoUrl = BizNano.CreateNano(model.BigUrl, GetUniqueUserId());
            if (!string.IsNullOrEmpty(model.NanoUrl))
                model.IsNanoAvail = true;
            return View(model);
        }
        public ActionResult Migrate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Go");
            else
            {
                var bigUrl = BizNano.GetBigUrl(id);
                if (string.IsNullOrEmpty(bigUrl))
                    return RedirectToAction("Go");
                else
                    return Content(string.Format("<script language='javascript' type='text/javascript'>location.href='{0}';</script>", bigUrl));
            }
        }
        public ViewResult GenerateNano(NanoModel model)
        {
            if (!string.IsNullOrEmpty(model.BigUrl) && model.BigUrl.Contains('.'))
            {
                model.Nano = BizNano.CreateNano(model.BigUrl, GetUniqueUserId());
                model.NanoUrl = string.Format("{0}/{1}", Uri.UriSchemeHttp + Uri.SchemeDelimiter + "localhost/Creation", model.Nano);
                model.IsNanoAvail = true;
            }
            return View("Go", model);
        }
    }
}

srCreation/Creation/Views/NanoGen/Go.cshtml
@model srEntity.NanoModel
@section scripts
    {
    <script type="text/javascript" language="javascript">
        $(document).on('click', '#execNanoGen', function () {
            var urlEntered = $('#BigUrl').val();
            if (urlEntered.split('.').length > 1)
                return true;
            else {
                SetErr('Please provide valid URL to convert.');
                return false;
            }
        });
    </script>
}
@using (Html.BeginForm())
{
    <fieldset>
        <table id="tNanoGen" style="width:100%">
            <tr>
                <td>
                    Large URL
                </td>
                <td>
                    @Html.TextBoxFor(m => m.BigUrl, new { placeholder = "Enter large url here.", @class = "textPadding bigBox", name = "txtBigUrl" })
                </td>
            </tr>
            @if (Model.IsNanoAvail)
            {
                <tr>
                    <td>
                        Nano Url
                    </td>
                    <td>
                        <a id="sNanoGenerated" href="@Model.NanoUrl">
                            @Model.NanoUrl
                        </a>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="2" style="text-align:center;">
                    <input type="submit" formaction="@Url.Action("GenerateNano","NanoGen")" id="execNanoGen" class="btn btn-primary" value="Generate Nano" />
                </td>
            </tr>
        </table>
    </fieldset>
}